api/src/Entity/Activity.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ActivityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ActivityRepository::class)]
#[ApiResource]
class Activity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 1000)]
    private ?string $name = null;

    #[ORM\Column(length: 3000)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\GreaterThan('today')]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $starting_time = null;

    #[ORM\Column]
    private ?bool $outdoor = null;

    #[ORM\Column(type: Types::BLOB, nullable:true)]
    private $image = null;

    #[ORM\Column]
    private ?bool $open = null;

    #[ORM\ManyToOne(inversedBy: 'initiateActivities')]
    private ?User $owner = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'joinActivities')]
    private Collection $participants;

    #[ORM\Column]
    private ?int $numberOfParticipants = null;

    #[ORM\OneToMany(mappedBy: 'activity', targetEntity: ActivityQuestion::class, orphanRemoval: true, cascade:['persist'])]
    private Collection $activityQuestions;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\OneToMany(mappedBy: 'activity', targetEntity: Conversation::class)]
    private Collection $conversations;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
        $this->activityQuestions = new ArrayCollection();
        $this->conversations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStartingTime(): ?\DateTimeInterface
    {
        return $this->starting_time;
    }

    public function setStartingTime(\DateTimeInterface $starting_time): self
    {
        $this->starting_time = $starting_time;

        return $this;
    }

    public function isOutdoor(): ?bool
    {
        return $this->outdoor;
    }

    public function setOutdoor(bool $outdoor): self
    {
        $this->outdoor = $outdoor;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    public function isOpen(): ?bool
    {
        return $this->open;
    }

    public function setOpen(bool $open): self
    {
        $this->open = $open;

        return $this;
    }


    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(User $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants->add($participant);
            $participant->addJoinActivity($this);
        }

        return $this;
    }

    public function removeParticipant(User $participant): self
    {
        if ($this->participants->removeElement($participant)) {
            $participant->removeJoinActivity($this);
        }

        return $this;
    }


    public function getNumberOfParticipants(): ?int
    {
        return $this->numberOfParticipants;
    }

    public function setNumberOfParticipants(int $numberOfParticipants): self
    {
        $this->numberOfParticipants = $numberOfParticipants;

        return $this;
    }

    /**
     * @return Collection<int, ActivityQuestion>
     */
    public function getActivityQuestions(): Collection
    {
        return $this->activityQuestions;
    }

    public function addActivityQuestion(ActivityQuestion $activityQuestion): self
    {
        if (!$this->activityQuestions->contains($activityQuestion)) {
            $this->activityQuestions->add($activityQuestion);
            $activityQuestion->setActivity($this);
        }

        return $this;
    }

    public function removeActivityQuestion(ActivityQuestion $activityQuestion): self
    {
        if ($this->activityQuestions->removeElement($activityQuestion)) {
            // set the owning side to null (unless already changed)
            if ($activityQuestion->getActivity() === $this) {
                $activityQuestion->setActivity(null);
            }
        }

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection<int, Conversation>
     */
    public function getConversations(): Collection
    {
        return $this->conversations;
    }

    public function addConversation(Conversation $conversation): self
    {
        if (!$this->conversations->contains($conversation)) {
            $this->conversations->add($conversation);
            $conversation->setActivity($this);
        }

        return $this;
    }

    public function removeConversation(Conversation $conversation): self
    {
        if ($this->conversations->removeElement($conversation)) {
            // set the owning side to null (unless already changed)
            if ($conversation->getActivity() === $this) {
                $conversation->setActivity(null);
            }
        }

        return $this;
    }
}

api/src/Form/ActivityType.php
<?php

namespace App\Form;
use App\Entity\Activity;
use App\Entity\User;
use App\Form\ActivityQuestionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class ActivityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    { 
        $years = range(date('Y'), date('Y')+2);
        $builder
            ->add('name')
            ->add('description')
            ->add('duration')
            ->add('location')
            ->add('date',DateType::Class, array(
                'widget' => 'choice',
                'years' => $years,
            'data' => new \DateTime(),
                
              ))
            ->add('starting_time')
            ->add('outdoor')
            ->add('open')
            ->add('numberOfParticipants')
            // ->add('owner', EntityType::class,[
            //     'class' => User::class,
            //     'choice_label' => 'username',
            // ])
            ->add('activityQuestions', CollectionType::class, [
                'entry_type' => ActivityQuestionType::class,
                'entry_options' => ['label' => false],
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Activity::class,
        ]);
    }
}

api/src/Controller/ActivityController.php
<?php

namespace App\Controller;

use App\Entity\Activity;
use App\Form\ActivityType;
use App\Repository\ActivityRepository;
use App\Repository\QcmRepository;
use App\Service\ActivityService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;


#[Route('/app/activity')]
#[IsGranted('ROLE_USER')]
class ActivityController extends AbstractController
{
    #[Route('/', name: 'app_activity_index', methods: ['GET'])]
    public function index(ActivityRepository $activityRepository, Request $request ): Response
    {
        $page = $request->query->get('page',1);
        $itemsPerPage = 10 ;
        $list = $activityRepository->findBy( ['open'=>true], ['date'=>'ASC'], $itemsPerPage, ($page - 1) * $itemsPerPage) ;
        return $this->render('activity/index.html.twig', [
            'activities' => $list
            
        ]);
    }

    #[Route('/my/', name: 'app_activity_my', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function myIndex(ActivityRepository $activityRepository): Response
    {
        return $this->render('activity/index.html.twig', [
            'activities' => $activityRepository->findBy(['owner'=>$this->getUser()]) 
         
        ]);
    }

    // #[Route('/new', name: 'app_activity_new', methods: ['GET', 'POST'])]
    // #[IsGranted('ROLE_USER')]
    // public function new(Request $request, ActivityService $activityService, ActivityRepository $activityRepository, QcmRepository $qcmRepository): Response
    // {
    //     $activity = $activityService->getPrefiledActivity();
    //     $form = $this->createForm(ActivityType::class, $activity);
    //     $form->handleRequest($request);
    
    //     $session = $request->getSession();
    //     if (!$session->has('current_step')) {
    //         $session->set('current_step', 1);
    //     }
    
    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $activity->setOwner($this->getUser());
    //         $activityRepository->save($activity, true);
    
    //         // Mettez à jour la session current_step pour passer à l'étape suivante
    //         $session->set('current_step', $session->get('current_step') + 1);
    
    //         return $this->redirectToRoute('app_activity_new', [], Response::HTTP_SEE_OTHER);
    //     }
    
    //     return $this->render('activity/new.html.twig', [
    //         'activity' => $activity,
    //         'form' => $form->createView(),
    //         'current_step' => $session->get('current_step'),
    //     ]);
    // }

    #[Route('/new', name: 'app_activity_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function new(Request $request, ActivityService $activityService, ActivityRepository $activityRepository, QcmRepository $qcmRepository): Response
    {
        $activity = $activityService->getPrefiledActivity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        $session = $request->getSession();
        if ($form->isSubmitted() && $form->isValid()) {
            $activity->setOwner($this->getUser());
            $activityRepository->save($activity, true);

            // Réinitialiser la session pour recommencer depuis l'étape 1
            $session->remove('current_step');

            // Rediriger vers la liste des activités
            return $this->redirectToRoute('app_activity_index');
        }

        if (!$session->has('current_step')) {
            $session->set('current_step', 1);
        }

        return $this->render('activity/new.html.twig', [
            'activity' => $activity,
            'form' => $form->createView(),
            'current_step' => $session->get('current_step'),
        ]);
    }
    
    #[Route('/{id}', name: 'app_activity_show', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function show(Activity $activity): Response
    {
        return $this->render('activity/show.html.twig', [
            'activity' => $activity,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_activity_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function edit(Request $request, Activity $activity, ActivityRepository $activityRepository): Response
    {
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $activity->setOwner($this->getUser());
            $activityRepository->save($activity, true);

            return $this->redirectToRoute('app_activity_my', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('activity/edit.html.twig', [
            'activity' => $activity,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_activity_delete', methods: ['POST'])]
    #[IsGranted('ROLE_USER')]
    public function delete(Request $request, Activity $activity, ActivityRepository $activityRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$activity->getId(), $request->request->get('_token'))) {
            $activityRepository->remove($activity, true);
        }

        return $this->redirectToRoute('app_activity_index', [], Response::HTTP_SEE_OTHER);
    }
}

api/templates/activity/_delete_form.html.twig
<form method="post" action="{{ path('app_activity_delete', {'id': activity.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activity.id) }}">
    <button class="btn">Delete</button>
</form>

api/templates/activity/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Activity{% endblock %}

{% block body %}
    <h1>Edit Activity</h1>

    {{ include('activity/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_activity_index') }}">back to list</a>

    {{ include('activity/_delete_form.html.twig') }}
  
{% endblock %}

api/templates/activity/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity index{% endblock %}

{% block body %}
	<div class="d-flex justify-content-center"> 
		<a href="{{ path('app_activity_new') }}" class="btn custom-button-activity">Create new activity</a>
	</div>

	<div class="d-flex justify-content-center">
		<h1>or join activity:</h1>
	</div>

	<div class="row row-cols-2 row-cols-md-3">
		{% set imageIndex = 1 %}
		{% for activity in activities %}
			{% set imagePath = '/images/activities/image' ~ imageIndex ~ '.jpg' %}
			<div class="col mb-4">
				<div class="card h-100">
					<!--Card image-->
					<div class="view overlay">
						<img class="card-img-top" src="{{ imagePath }}" alt="Card image cap" style="height: 200px; object-fit: cover;">
					</div>

					<!--Card content-->
					<div class="card-body">
						<!--Title-->
						<h4 class="card-title">{{ activity.name }} / {{ activity.date ? activity.date|date('Y-m-d') : '' }}</h4>
						<!--Text-->
						<p class="card-text">
							⏰{{ activity.startingTime ? activity.startingTime|date('H:i:s') : '' }}<br>
							{{ activity.description }}<br>
							Organized by: {{ activity.owner.getUsername }}<br>
							with {{ activity.numberOfParticipants }} participants<br>
							in {{ activity.location }}
						</p>
						<!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
						<a href="{{ path('app_message', {'id': activity.id}) }}" class="btn custom-button-activity">
							CONTACT {{ activity.owner.getUsername }}
						</a>
						<a href="{{ path('app_activity_edit', {'id': activity.id}) }}" class="btn btn-light-blue btn-md">Edit</a>
						{% if app.user.id == activity.owner.id %}
							{# <a href="{{ path('app_activity_show', {'id': activity.id}) }}" class="btn custom-button-activity">Show</a> #}
						{% endif %}
					</div>
				</div>
			</div>
			{% set imageIndex = imageIndex + 1 %}
			{% if imageIndex > 8 %}
				{% set imageIndex = 1 %}
			{% endif %}
		{% endfor %}
	</div>
{% endblock %}



{# {% extends 'base.html.twig' %}

{% block title %}Activity index
{% endblock %}

{% block body %}

	<div class="d-flex justify-content-center"> 
	<a href="{{ path('app_activity_new') }}" button class="btn custom-button-activity">Create new activity</a>
	</div>

	<div class="d-flex justify-content-center">
	<h1>or join activitiy :</h1>
	</div>

	<div class="row row-cols-2 row-cols-md-3">
	
	{% for activity in activities %}
		
			<div class="col mb-4">
				<div class="card h-100">
					<!--Card image-->
					<div class="view overlay">


						<img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/16.webp" alt="Card image cap" />

					</div>

					<!--Card content-->
					<div class="card-body">

						<!--Title-->
						<h4 class="card-title">{{ activity.name }} /
							{{ activity.date ? activity.date|date('Y-m-d') : '' }}</h4>
						<!--Text-->
						<p class="card-text">⏰{{ activity.startingTime ? activity.startingTime|date('H:i:s') : '' }}
							<br>{{ activity.description }}
							<br>Organized by :
							{{ activity.owner.getUsername }}
							<br>
							with
							{{ activity.numberOfParticipants }}
							participants
							<br>
							in
							{{ activity.location }}
						</p>
						<!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
						<a href="{{ path('app_message', {'id': activity.id})}}" class="btn custom-button-activity">
                            CONTACT {{ activity.owner.getUsername }}
						</a>
						<a href="{{ path('app_activity_edit', {'id': activity.id}) }}" button class="btn btn-light-blue btn-md" >Edit</a>	
						{% if app.user.id == activity.owner.id %}
								{# <a href="{{ path('app_activity_show', {'id': activity.id}) }}" button class="btn custom-button-activity">Show</a> #}
			
						{# {% endif %}
					</div>
				</div>
			</div>
		
	{% endfor %}
</div>
{% endblock %} #} 

	{# {% for activity in activities %}
		<tr>
			<td>{{ activity.owner.getUsername() }}</td>
			<td>{{ activity.location}}</td>
			<td>{{ activity.name }}</td>
			<td>{{ activity.description }}</td>
			<td>{{ activity.duration }}</td>
			<td>{{ activity.date ? activity.date|date('Y-m-d') : '' }}</td>
			<td>{{ activity.startingTime ? activity.startingTime|date('H:i:s') : '' }}</td>
			<td>{{ activity.outdoor ? 'Yes' : 'No' }}</td>
			<td>{{ activity.image }}</td>
			<td>{{ activity.open ? 'Yes' : 'No' }}</td>
			<td>{{ activity.numberOfParticipants }}</td>

			<td>
				<a href="{{ path('app_message', {'id': activity.id})}}">contact</a>
			</td>
			{% if app.user.getUsername == activity.owner.getUsername %}
				<td>
					<a href="{{ path('app_activity_show', {'id': activity.id}) }}">show</a>
					<a href="{{ path('app_activity_edit', {'id': activity.id}) }}">edit</a>
				</td>
			{% endif %}
		</tr>
	{% else %}
		<tr>
			<td colspan="11">no records found</td>
		</tr>
	{% endfor %} #}

api/templates/activity/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Activity{% endblock %}

{% block body %}
<body class="gradient-custom">
    <div class="d-flex justify-content-center">
        <h1>Create new Activity</h1>
    </div>

    <div class="d-flex justify-content-center">
        {{ include('activity/_form.html.twig') }}
    </div>
    
    <div class="d-flex justify-content-center">
        <a href="{{ path('app_activity_index') }}">Back to Activities</a>
    </div>
¸</body>
{% endblock %}

api/templates/activity/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity{% endblock %}

{% block body %}
    <h1>Activity</h1>
{% for activity in activities %}
    <table class="table">
        <tbody>
            <tr>
                <th>Owner</th>
                <td>{{ activity.Owner.getUsername }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ activity.location }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ activity.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ activity.description }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ activity.duration }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ activity.date ? activity.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Starting_time</th>
                <td>{{ activity.startingTime ? activity.startingTime|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Outdoor</th>
                <td>{{ activity.outdoor ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Open</th>
                <td>{{ activity.open ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>NumberOfParticipants</th>
                <td>{{ activity.numberOfParticipants }}</td>
            </tr>
            
        </tbody>
    </table>

    <a href="{{ path('app_activity_index') }}">Back to activity list</a>

    <a href="{{ path('app_activity_edit', {'id': activity.id}) }}">Edit</a>

    {{ include('activity/_delete_form.html.twig') }}
{% endblock %}